apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig1
  labels:
    app: swiggy
data:
  name: "shashank"
  role: "seniormembertechnical"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  labels:
    app: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
      - name: cont2
        image: shashankudari/devopscourse:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: myconfig
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006

